# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 09:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_surgery', models.DateTimeField(blank=True, default=datetime.datetime(1800, 1, 1, 0, 0))),
                ('icd10procedure', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField(blank=True, default=datetime.datetime(1800, 1, 1, 0, 0))),
                ('icd10desc', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
